app-config:
  title: "Interactive Maps - Aerospacelab"
  description: "Back-end for Interactive Maps application"
  summary: "Technical Assignment"
  version: "0.1-ALPHA"
  terms_of_service: "#"
  iss_id: 25544
  apis:
    # A way to store all external api info for easier management.
    sat_loc:
      url: "https://api.wheretheiss.at/v1/satellites/"
  services:
    # This service is used to poll the iss position every 20sec (max). This way we decouple our database and the frontend from this restriction
    # As an alternative we could use an @app.middleware("http") in our main.py and keep track of the timedelta there
    pull_position:
      enabled: true
      entrypoint: "pull_position_task.main"
      freq: 20
